### ISSUE TITLE
Issue with PyQt4.QtWebKit

### ISSUE THREAD

**Issue by LastGenomeBender** [djhn75/RNAEditor#19]
Hello, 
I am usuing Ubuntu 18.04 LTS when I run RNAeditor.py I get the following error:
`Traceback (most recent call last):
  File "/home/ahadli/Downloads/RNAEditor/RNAEditor.py", line 322, in <module>
    from ui.GuiView import GuiView
  File "/home/ahadli/Downloads/RNAEditor/ui/GuiView.py", line 4, in <module>
    from ui.GuiControll import GuiControll
  File "/home/ahadli/Downloads/RNAEditor/ui/GuiControll.py", line 17, in <module>
    from ui.ResultTab import ResultTab
  File "/home/ahadli/Downloads/RNAEditor/ui/ResultTab.py", line 5, in <module>
    from PyQt4.QtWebKit import QWebView
ModuleNotFoundError: No module named 'PyQt4.QtWebKit'`
I would like to mention that I installed all of the dependencies, including PyQt4. As I learned from this [issue],(https://github.com/Xanthos-Eve/vintel/issues/159) QtWebKit is not part of the PyQt4 package. Is there any way to resolve this issue? Thanks in advance.

Regards.

**Comment by djhn75** [comment]
Dear ahadli, thank for bringing up this issue. This seems to be a general problem for newer version of ubuntu and PyQt4. Could you check if there is a folder named **QtWebKit** in **/usr/lib/python2.7/dist-packages/PyQt4/** if not you could exchange your folder PyQt4 with PyQt4 folder in the in the linked archiv. This countains the QtWebKit Library.

https://drive.google.com/open?id=1asmzQ81wQFyr_l8ss8eb07dKTKfioZ0q
  
Currently i don't have an easier solution for this problem.
But i am currently working on a version of RNAEditor which is compatible to Python3 and PyQt5.

Best regards David

**Comment by ahadli** [comment]
Dr John,
I performed the steps you advised and ended up with the following error:
`Traceback (most recent call last):
  File "/home/ahadli/Downloads/RNAEditor/RNAEditor.py", line 9, in <module>
    from Helper import Helper, Parameters
  File "/home/ahadli/Downloads/RNAEditor/Helper.py", line 13, in <module>
    from PyQt4 import QtCore
ImportError: cannot import name 'QtCore'`

When I examined the PyQt4 folder you linked, I found a file named `QtCore.x86_64-linux-gnu.so`. Then I changed the filenames to `QtCore.so` and ran the code again. Output:
`Traceback (most recent call last):
  File "/home/ahadli/Downloads/RNAEditor/RNAEditor.py", line 9, in <module>
    from Helper import Helper, Parameters
  File "/home/ahadli/Downloads/RNAEditor/Helper.py", line 13, in <module>
    from PyQt4 import QtCore
ImportError: /usr/lib/python3/dist-packages/PyQt4/QtCore.so: undefined symbol: _Py_RefTotal
`
Thanks in advance.
Regards,
Farid Ahadli.
