### ISSUE TITLE
RNA Editor fails at indexing BAM file step

### ISSUE THREAD

**Issue by AliSajid** [djhn75/RNAEditor#24]
Hi,

I am trying to develop a pipeline including your RNA Editor in it. However, when I try to use it, I run into an error. The software quits when it is at the indexing bam file step.

I have tried running it manually and samtools complains about the bamfile not being sorted or being corrupt.

The log file is as follows:

`*** INFO:    CHECK DEPENDENCIES ***
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
*** INFO:    Dependencies satisfied ***
*** INFO:    *** Start RnaEditor with: *** ***
*** INFO:    	 FastQ-File_1: ./SRR3438555_1.fastq ***
*** INFO:    	 FastQ-File_2: ./SRR3438555_2.fastq ***
*** INFO:    	 outfilePrefix:./rnaEditor/SRR3438555_1/SRR3438555_1 ***
*** INFO:    	 refGenome:/users/PJS0313/asimami/scratch/GRCH38/Homo_sapiens.GRCh38.dna.primary_assembly.fa ***
*** INFO:    	 dbsnp:/users/PJS0313/asimami/scratch/GRCH38/dbSNP.vcf ***
*** INFO:    	 sourceDir:/users/PJS0313/asimami/.local/bin/ ***
*** INFO:    	 threads:20 ***
*** INFO:    	 maxDiff:0.04 ***
*** INFO:    	 seedDiff:2 ***
*** INFO:    	 paired:True ***
*** INFO:    	 keepTemp:True ***
*** INFO:    	 overwrite:False ***
*** INFO:     ***
*** INFO:    [Mon Oct 14 12:16:39 2019] * * * Align first Reads with BWA * * * ***
	*** [DONE] Duration [0:09:08.359643] ***
*** INFO:    [Mon Oct 14 12:25:47 2019] * * * Align second Reads with BWA * * * ***
	*** [DONE] Duration [0:09:01.090889] ***
*** INFO:    [Mon Oct 14 12:34:48 2019] * * * convert sai to sam * * * ***
	*** [DONE] Duration [0:59:19.445871] ***
*** INFO:    [Mon Oct 14 13:34:08 2019] * * * Sort Bam File * * * ***
	*** [DONE] Duration [0:18:01.413584] ***
*** INFO:    [Mon Oct 14 13:52:09 2019] * * * Index Bam File * * * ***
None

Traceback (most recent call last):
  File "/users/PJS0313/asimami/scratch/RNAEditor-master/RNAEditor.py", line 75, in run
    self.startAnalysis()
  File "/users/PJS0313/asimami/scratch/RNAEditor-master/RNAEditor.py", line 98, in startAnalysis
    mapResultFile=self.mapFastQ.startAnalysis()
  File "/users/PJS0313/asimami/scratch/RNAEditor-master/MapFastq.py", line 137, in startAnalysis
    Helper.proceedCommand("Index Bam File", cmd, samFile, bamFile+".bai", self.rnaEdit)
  File "/users/PJS0313/asimami/scratch/RNAEditor-master/Helper.py", line 286, in proceedCommand
    Helper.error(description+ " failed!!!",logFile,textField)
  File "/users/PJS0313/asimami/scratch/RNAEditor-master/Helper.py", line 753, in error
    raise Exception("\n\n" + Helper.prefix + "ERROR:    " + message + Helper.praefix + "\n\n")
Exception: 

*** ERROR:    Index Bam File failed!!! ***

Traceback (most recent call last):
  File "/users/PJS0313/asimami/scratch/RNAEditor-master/RNAEditor.py", line 77, in run
    Helper.error("RnaEditor Failed",self.logFile,self.textField)
  File "/users/PJS0313/asimami/scratch/RNAEditor-master/Helper.py", line 753, in error
    raise Exception("\n\n" + Helper.prefix + "ERROR:    " + message + Helper.praefix + "\n\n")
Exception: 

*** ERROR:    RnaEditor Failed ***`

Can you help with this?

**Comment by djhn75** [comment]
This sound like a problem with Samtools.
Could you check if the sorted Bam file was created properly?

**Comment by AliSajid** [comment]
Checking using the various tricks including https://github.com/IARCbioinfo/BAM-tricks#check-if-bam-file-is-sorted shows me that it was indeed sorted correctly. 

It appears that samtools is unable to support BAI indices for large genomes. I am filing a request there as well. Meanwhile, if samtools indeed has trouble, the workflow will need to be adjusted here too. Will keep you updated.
